Repository Elaniobro/MMM-nyc-transit, pull requests merged in 2021-12, with the labels that each got.

#64 Fix reversed upTown and downTown arrival filtering
  node_helper.js
Labels: 🐛 bug, :white_small_square: patch

#67 ci(actions): add ESLint run cmd
  .github/workflows/lint.yml
Labels: ⚙️ - CICD

#69 build(linter): add commitizen for commits
  package.json
  yarn.lock
Labels: ⚙️ - CICD

#71 Add scope to module name for npm installs
  .npmrc
  package.json
Labels: :white_large_square: major, ⚙️ - CICD
